### ISSUE TITLE
Is DIscord Running? and Pipe Window Problem

### ISSUE THREAD

**Issue by AyushPande123** [maximmax42/Discord-CustomRP#27] opened 2021-08-15 09:52 UTC
**Describe the bug**
whenever I click connect it tells Connecting and tells that Connection Failed, (is discord running?). and sometimes a window comes and the title will be "Pipe" and there is a number selecting the option and there is none other was to close except the close button
**To Reproduce**
1. click connect
2. and we can see error Connection Failed (is discord running?)
3. and the pipe window comes anytime

**Expected behavior**
after clicking connect it shole show the RP

**Screenshots**
![image](https://user-images.githubusercontent.com/77191080/129474371-2531c83e-203d-4cea-8704-e619ef7a01a4.png)

![image](https://user-images.githubusercontent.com/77191080/129474463-8d048e7a-32b3-4235-bfa1-c024eca541a5.png)

**Useful Info**
 - Windows Version: Windows 11 21h2
 - Application Version: 1.11.2

**Additional context**
none

**Comment by maximmax42** [comment] 2021-08-15 09:57
Pipe window comes up if you hold Ctrl while clicking the connect button. Leave it at -1.
Did you read FAQ and try to add the app in a firewall/antivirus exception?

**Comment by AyushPande123** [comment] 2021-08-15 10:06
no

but you told me to keep it -1 so when I kept it and connected it then it connected Thanks.

btw what is that pipe window?

**Comment by maximmax42** [comment] 2021-08-15 10:14
So the problem is solved? I'll close the issue then.
Pipe is basically a slot Discord is taking up. If you have only 1 Discord client you don't have to worry about it at all, it'll always be on pipe 0 (-1 means "search first one available), but if you're running more than one client, changing a pipe number will basically choose what client to display presence in.

**Closed by maximmax42** 2021-08-15 10:14 UTC
Labels: bug
