### ISSUE TITLE
Some custom timestamps will cause connection to fail.

### ISSUE THREAD

**Issue by MazeCow** [maximmax42/Discord-CustomRP#197] opened 2023-02-13 21:48 UTC
Using a custom timestamp that goes too far back will cause CustomRP to fail connections.
Ex. 1/1/1970 7:00:00PM

**Comment by maximmax42** [comment] 2023-02-13 23:05
I mean, why are you using something so far back? Also you shouldn't be able to pick something that's before 1/1/1970 0:00:00 UTC, but maybe there's a fault with my code somewhere and that's why it's failing.

**Comment by takoda121** [comment] 2023-02-21 16:55
Not a bug, just discord not accepting anything before 9/9/2001 (yes 9/9/01).

**Comment by takoda121** [comment] 2023-02-21 17:03
> > Not a bug, just discord not accepting anything before 9/9/2001 (yes 9/9/01).
> 
> Can't reproduce, app connects just fine with anything between 1/1/1970 and 9/9/01.

I tried: 9/9/01 3AM (Started working at 3:46:40). The app connects fine but as I see the rpc is telling: "00:00 elapsed".

**Comment by maximmax42** [comment] 2023-02-21 17:05
> 

*Oh.* Okay, I can reproduce that.

**Comment by MazeCow** [comment] 2023-02-22 21:47
Yeah idk. Still doesn't work for me but other dates work.

**Comment by maximmax42** [comment] 2023-02-22 22:01
Well for your original issue, I mean, just don't set a date in January 1st of 1970, idk.

**Comment by maximmax42** [comment] 2023-02-26 20:45
Fixed by making the minimum date 2001-09-09 1:46:40 UTC (1000000000 in unix). Update will release in like a couple of minutes.

**Closed by maximmax42** 2023-02-26 20:45 UTC
Labels: bug
